version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/python:3.8.1-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
          CHROME_BINARY_LOCATION: /usr/bin/google-chrome
          CHROME_DRIVER_LOCATION: /usr/local/bin/chromedriver
    working_directory: ~/CircleCIWork

commands:
  restore:
    steps:
      - when:
          condition:
            equal: [ requires-io-master, << pipeline.git.branch >> ]
          steps:
            - restore_cache:
                key: mmscreenshot-v11-{{ .Branch }}-{{ checksum "Pipfile" }}
            - run:
                command: |
                  echo restore by Pipfile
      - unless:
          condition:
            equal: [ requires-io-master, << pipeline.git.branch >> ]
          steps:
            - restore_cache:
                key: mmscreenshot-v11-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - run:
                command: |
                  echo restore by Pipfile.lock

  save:
    parameters:
      keyfile:
        type: string
        default: Pipfile.lock
    steps:
      - save_cache:
          paths:
            - ".venv"
          key: mmscreenshot-v11-{{ .Branch }}-{{ checksum "<< parameters.keyfile >>" }}
      - run:
          command: |
            echo save << parameters.keyfile >> 

jobs:

  setup:
    executor: my-executor
    steps:
      - checkout
      - when:
          condition:
            equal: [ requires-io-master, << pipeline.git.branch >> ]
          steps:
            - run: echo ----------- requires ---------------- 
            - restore
            - run:
                name: install_and_pipenv_lock
                command: |
                  python --version
                  sudo pip install pipenv
                  pipenv install --dev
                  pipenv lock
                  pipenv run pip install -e .
            - save:
                keyfile: Pipfile
      - unless:
          condition:
            equal: [ requires-io-master, << pipeline.git.branch >> ]
          steps:
            - run: echo ----------- normal ----------------
            - restore
            - run:
                name: install
                command: |
                  python --version
                  sudo pip install pipenv
                  pipenv sync --dev
                  pipenv run pip install -e .
            - save:
                keyfile: Pipfile.lock
            - store_artifacts:
                path: ./Pipfile.lock

  lint:
    executor: my-executor
    steps:
      - checkout
      - restore
      - run:
          name: lint
          command: |
            pipenv run lint

  test:
    executor: my-executor
    steps:
      - checkout
      - when:
          condition:
            equal: [ requires-io-master, << pipeline.git.branch >> ]
          steps:
            - restore
      - unless:
          condition:
            equal: [ requires-io-master, << pipeline.git.branch >> ]
          steps:
            - restore
      - run:
          name: test
          command: |
            pipenv run ut
            bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: ./screenshot.png

workflows:
  version: 2.1
  build-and-test-workflow:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
