version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/python:3.8.1-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
          CHROME_BINARY_LOCATION: /usr/bin/google-chrome
          CHROME_DRIVER_LOCATION: /usr/local/bin/chromedriver
    working_directory: ~/CircleCIWork

commands:
  restore:
    steps:
      - restore_cache:
          key: mmscreenshot-v11-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            echo normal_restore

  save:
    steps:
      - save_cache:
          paths:
          key: mmscreenshot-v11-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            echo normal_save

  lint:
    steps:
      - run:
          command: |
            pipenv run lint

  test:
    steps:
      - run:
          command: |
            pipenv run ut
            bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: ./screenshot.png

jobs:

  setup:
    executor: my-executor
    steps:
      - checkout
      - restore
      - run:
          name: install
          command: |
            python --version
            sudo pip install pipenv
            pipenv sync --dev
            pipenv run pip install -e .
      - save

  setup_for_requiresio:
    executor: my-executor
    steps:
      - checkout
      - restore
      - run:
          name: install
          command: |
            python --version
            sudo pip install pipenv
            pipenv install --dev
            pipenv lock
            pipenv run pip install -e .
      - save
      - store_artifacts:
          path: ./Pipfile.lock

  lint:
    executor: my-executor
    steps:
      - checkout
      - restore
      - lint

  test:
    executor: my-executor
    steps:
      - checkout
      - restore
      - test

workflows:
  version: 2.1
  build-and-test-workflow:
    jobs:
      - setup:
          filters:
            branches:
              ignore: /requires-io-master/
      - setup_for_requiresio:
          filters:
            branches:
              only: /requires-io-master/
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
